#!/bin/bash

#set -x

LOG="/var/log/cron.log"

lsof | grep output > /dev/null
if [ $? -eq 0 ]
then
    echo "crond: rip in progress. exiting" >> $LOG
    exit 1
fi

pgrep -lf disc:0 > /dev/null
if [ $? -eq 0 ]
then
    echo "crond: disc rip in progress. exiting" >> $LOG
    exit 1
else
    find /output -name processed.dat | awk -F '/' '{print $3}' > /output/exclude_list
    echo "exclude_list" >> /output/exclude_list
    echo "output" >> /output/exclude_list
    ls -ld /output/* | awk -F '/' '{print $3}' | grep -vf /output/exclude_list > /output/output.txt
    if [ ! -s /output/output.txt ]
    then
        echo "crond: nothing to process. exiting" >> $LOG
    fi

    for i in `cat /output/output.txt`
    do
        cd /output/${i}
        ls *.mkv > list.txt
        for m in `cat list.txt`
        do
            p=`/opt/makemkv/bin/makemkvcon -r info file:$m --cache=2048 | /usr/local/bin/findfeature.pl`
            echo "$m $p" >> scratch.txt
        done
    done

    for i in `cat /output/output.txt`
    do
        cd /output/${i}
         movietitle=`pwd | awk -F '/' '{print $3}' | tr '[:upper:]' '[:lower:]'`
         featuremkv=`sort -r -k 2 scratch.txt | head -1 | awk '{print $1}'`
         mv $featuremkv /handbrake/${movietitle}.mkv
         mv scratch.txt processed.dat
    done
fi
